"""Add tribute_contents table for dynamic section editing

Revision ID: 565d79ca6581
Revises: aa7eb4d68dbe
Create Date: 2026-07-14 08:28:59.668684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565d79ca6581'
down_revision = 'aa7eb4d68dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tribute_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_tribute_contents_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tribute_contents')),
    sa.UniqueConstraint('section_key', name=op.f('uq_tribute_contents_section_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tribute_contents')
    # ### end Alembic commands ###
