"""add active_step to user

Revision ID: 7f8f8c51e723
Revises: 565d79ca6581
Create Date: 2026-07-30 10:49:55.488017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8f8c51e723'
down_revision = '565d79ca6581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_step', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('wish_likes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_likes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active_step')

    # ### end Alembic commands ###
